### PR TITLE
fix flag height

### PR DESCRIPTION
**Pull request by chance-nb**
I just noticed that flags are consistently 1 character higher than specified. Subtracting 1 from the users input (except in vertical mode) fixes this. Also changed the help message because it is now accurate and changed the error check for the height to < 0.

I'm so sorry for not noticing this earlier.

### CODE REVIEW

**Comment by 0xf0xx0** [comment]
i think the issue is actually in the code i wrote :O

if you add `currLine` to the stripes, you can see why its adding a extra stripe; `currLine` starts at 0, so when the user passes a height of, say, `24`, it goes from 0-24, which is actually 2**5** in length
but only in horizontal flags, likely because i placed `currLine++` at the end of the loop for them. (70a0b1e)
does latest master 1ad4142 resolve this?

**Comment by chance-nb** [comment]
[`1ad4142`](https://github.com/ExperiBass/cli-pride-flags/commit/1ad4142da9b3cc0dbf1a4a85b88d39614776f436) creates a new problem of the last stripe of the flag always being 1 larger then it should be (in both vertical and horizontal mode). This also causes the first stripe to get cut off.
image

**Comment by chance-nb** [comment]
changing the comparison in line 126 of util.js to > fixed the issue.
but maybe just commit that directly since this PR is kind of bloated

**Comment by 0xf0xx0** [comment]
cherrypicked and merged :3

i wish github would pick up on that :\

**Pull request closed without merging**
