### PR TITLE
Create flags.html

### PR DESCRIPTION
**Pull request by KonkenBonken**
Added a quick visualization of all the flags in [flags.json](https://github.com/ExperiBass/cli-pride-flags/blob/97c771aa31140abf5d39b62ad1292beb6dba8874/src/flags.json)

### CODE REVIEW

**Comment by 0xf0xx0** [comment]
Pretty cool :D

**Comment by rhysperry111** [comment]
This is indeed pretty cool, but what exactly is the point? It adds an extra step to the process of adding flags, and I can't think of a reason to distribute a HTML file with a cli-based package

**Comment by 0xf0xx0** [comment]
Prolly gonna add it to my pages, can always npmignore it anyways

**Comment by KonkenBonken** [comment]
Yeah, idk about how it's going to be used in this package.
I made the page for myself using your flags.json and I thought I might as well share it

**Comment by rhysperry111** [comment]
It's all cool, dw. 

Maybe it'd be more useful to allow the script to parse flags.json and output in other formats? 
e.g. `cli-pride-flags [FLAG [...]] [--export=FILE]`

It does all seem rather complicated though

**Comment by KonkenBonken** [comment]
It is already generated from a script
Not that complicated

**Comment by 0xf0xx0** [comment]
finally got back to this, moved the file to https://experibass.github.io/flags.html, and im considering that output thing, although JSON is pretty versatile as is... 🤔

**Pull request merged**
