### PR TITLE
Add polyamorous flag & demienby/demigender flags

### PR DESCRIPTION
**Pull request by averyocean65**
Demigender:
grafik

Demienby:
grafik

Polyamorous:
grafik

### CODE REVIEW

**Comment by rhysperry111** [comment]
Potentially time for a new release on npm?

**Comment by 0xf0xx0** [comment]
once i can sit down and do so i will :3

**Comment by rhysperry111** [comment]
Take your time :333

**Comment by averyocean65** [comment]
In the meantime I can just add more pride flags if y'all don't mind

**Pull request merged**
